### ISSUE TITLE
Create project overview

### ISSUE THREAD

**Issue by Matthew-Burfield** [chingu-voyage3/bears-23#1]
1. What we are trying to achieve
2. User stories
3. High level features that we want to impliment

**Comment by chemok78** [comment]
https://docs.google.com/document/d/1gFNAAthqiMaCSa8GiXLrykWmD6JXg2JUoeQ-ELEQ_vo/edit?usp=sharing hi guys here is a document with the project scope. What I did was checking all the features of the Tide app and put that in writing with a MosSCoW analysis. I think the main discussion is what are the Must Haves (dealbreakers in the current sprint), Should Haves (important, but can be moved to other spring), Could Haves (Nice to have for user experience, but only if time and resources permit), Won't haves. I've done this as what makes sense to me now, but let's discuss

**Comment by Matthew-Burfield** [comment]
I think we should also add to this the tech stack and other technologies we want to do for this project. (i.e. react, redux, flow?, testing frameworks etc).

Also, maybe add our coding style guide? So are we all going to adapt to strict airbnb rules and use prettify?

Finally, I think we should move this document to become our GitHub project README.md

**Comment by chemok78** [comment]
Good idea to add it to our README.md. I'll do that.

And in that document we can add the tech stack decisions and add our coding style guide. I think we can do it in 1 document given the size of our project, right?

Question: do you want me to manage this document based on our decisions (i'm ok with that) or shall we have everyone edit/add content to it?

**Comment by Matthew-Burfield** [comment]
Well if we move it to the README.md then anyone can update it anyway.
